spring:
  application:
    name: example

  datasource:
    url: jdbc:postgresql://localhost:5432/example_db
    username: postgres
    password: kyalokyalo
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

#spring.profiles.active=dev, test


